//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

// If you use this template inside a _portable_ class library,
// then you should define the PORTABLE conditional compilation symbol
// in order to enable the creation of some necessary stub classes.
#if PORTABLE

namespace System
{
    /// <summary>
    ///   Fake, this is used only to allow serialization on portable platforms.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum, AllowMultiple = true, Inherited = false)]
    internal sealed class SerializableAttribute : Attribute
    {
        // This does nothing and should do nothing.
    }
}

#endif

